### PR TITLE
Add p19 - p24

### PR DESCRIPTION
**Pull request by tstat**
I needed these instances for my project. I don't know if these instances are desirable to have in the library, but if so here are p19 - p24.

### CODE REVIEW

**Comment by dbp** [comment]
@tomjaguarpaw I could really use these too!

**Comment by tomjaguarpaw** [comment]
Hello, sorry for the late response; I didn't get a notification about this until Daniel's reply.

I don't particularly object to adding these but I do wonder where it's going to stop.  Perhaps there's a better solution.  What do we all think?

@tstat and @dbp, do you actually want the instances for tuples, or do you want them because they are required for deriving the instances for record types with up to 24 fields?

**Comment by dbp** [comment]
I want them for deriving primarily. I wish that records didn't get that
big... But it happens :)

But I have used big tuples a couple times, when the main record is the
result of a join, and I didn't want to define separate records for the
tables that are just used for constructing the join. For example, I have a
twenty field record that gets eighteen fields from one table (defined with
a tuple) and two from another (also defined with a tuple).

**Comment by tstat** [comment]
In my case I just wanted it in order to derive instances for record types. I'm all for better solutions though, did you have something in mind?

**Comment by tomjaguarpaw** [comment]
If we keep adding more of these they should probably be generated with Template Haskell, but for now let's just add them longhand.

**Pull request merged**
