### PR TITLE
Raise max tuple size to 62.

### PR DESCRIPTION
**Pull request by hesselink**
This is the maximum that GHC allows. Turns out my record grew even more :) The good thing about this change is that it's probably the last time it'll change, at least until GHC raises the amount of tuples it has.

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
That's fine, though ideally the transformations for records shouldn't be going via tuples.

**Comment by hesselink** [comment]
Sure, that would be even better. Have you ever considered using generics for the record instances?

**Comment by tomjaguarpaw** [comment]
I don't think generics is powerful enough to derive these.  I just mean that you can use the record constructor, `(****)`, and `lmap`, rather than going via tuples.  I didn't realise this at the time I wrote the original code.

**Comment by hesselink** [comment]
Why wouldn't generics be powerful enough? Since generics are basically tuples and eithers, and currently tuples are powerful enough, it should be ok, but perhaps I'm missing some details. Maybe I'll have a look.

**Comment by tomjaguarpaw** [comment]
You might be right.  I couldn't get it to work out though.  In fact I couldn't even get it to derive `Traversable` instances (which is a simpler version of what we're doing).  If you can look at it and give your opinion that would be helpful to have on the record.

**Comment by hesselink** [comment]
I've looked into this a bit, and I've written a generic definition of `Default.def`. That means that you could make a default signature in the type class, and then a user (or template haskell) only has to write the instance line, and not the implementation. So something like:

```
instance (Default p a a', Default p b b', Default c c', ProductProfunctor p) => Default p (Foo a b c) (Foo a' b' c')
```

Would you be interested in this? The signatures are still quite big, so I doubt users would want to write them by hand, but at least this might remove all the tuple instances (they can go through `Generic` as well) and the TH only has to generate the instance header, not the body.

**Comment by tomjaguarpaw** [comment]
Yes, if you can write these with generics I will be very pleased!

**Pull request merged**
