### PR TITLE
Generic adaptors

### PR DESCRIPTION
**Pull request by Lysxia**
I prefer to leave internal modules exposed for documentation and maybe to let people hack around potential issues. But I see you already have some hidden modules. That's of course up to you.

### CODE REVIEW

**Comment by Lysxia** [comment]
Oh right TypeInType is quite new...

**Comment by Lysxia** [comment]
- I'm running into this issue which was only fixed for 8.0.1 https://ghc.haskell.org/trac/ghc/ticket/11699
  There is still a workaround I can try which shouldn't be too bad. One thing I don't think I can keep for pre-8 versions of GHC is the `Adaptor` type synonym.

- Closed type families were only introduced in GHC 7.8.4.  I guess I can do without. How imperative is it to you to remain compatible with older versions of GHC?

**Comment by tomjaguarpaw** [comment]
Debian stable only supportrs 7.6 so I'd like to keep supporting it until the next stable version of Debian is released.  Can we do something clever with conditional compilation?

**Comment by Lysxia** [comment]
Phew.

**Comment by Lysxia** [comment]
Wait, I think I found a better solution.

**Comment by Lysxia** [comment]
Not sure what's going wrong but this should compile otherwise.

**Comment by tomjaguarpaw** [comment]
What do you mean going wrong?  It seems to compile fine.

**Comment by Lysxia** [comment]
Now it's fine indeed :) I wrote that about my previous attempt earlier, [when Travis did not even get to compile the package (see jobs for GHC >= 7.8.4).](https://travis-ci.org/tomjaguarpaw/product-profunctors/builds/207467349)  
I think #19 suffered from the same issue.

**Comment by tomjaguarpaw** [comment]
This is really great!

**Pull request merged**
