### PR TITLE
Add `Default` instances for `Identity` and `Const`

### PR DESCRIPTION
**Pull request by duairc**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks, these seem reasonable.  Can I ask what you are using them for?

Could `Default p (Const a c) (Const b c)` be generalized to `Default p (Const a c) (Const b c')`?

**Comment by duairc** [comment]
I'm working on a vinyl-esque record library, and I want it to work seamlessly with Opaleye, and basically I need these instances to make a `Default` instance for my record type (well, I need `Identity`, I don't think I need `Const` yet, but I figured they should go together). It's all still in the pretty early stages so far, it'll be a while before I'll be able to properly release something (if ever), but I figured these instances could be useful regardless.

And yes, I think you're right about generalising `Const`.

**Comment by tomjaguarpaw** [comment]
Thanks!

**Comment by duairc** [comment]
No way, you did this seconds before I made another commit to that branch.

Basically, I've also added instances for `Tagged`. I need to add a couple of instances to `opaleye` as well (patch coming soon) for this to work, but basically the use case I want to support is as follows.

    type ID a = Tagged a PGInt4

Lets say I have a `foo` table with an `id` column. I want that column to have the type `Column (ID "foo")` instead of `Column PGInt4`. That way, when I join with `bar` table (which has a `foo_id` foreign key), I can do that in a type-safe way.

Do you think you merge this as well?

It adds a dependency on `tagged`, but it's a small, relatively standard package that we already transitively depend on via `profunctors` anyway.

**Comment by tomjaguarpaw** [comment]
Could you say a bit more about what you're doing?  I don't understand why you want to use `Column` rather than introduce your own type.

**Comment by duairc** [comment]
The `Column` bit isn't important.

Let's say you have a table called `foo`, and it has an `id` column of type `int` (`PGInt4`). Let's say you have another table called `bar`, and you want each `bar` to be associated with a `foo`. So in your `bar` table you have a column `bar_id` of type `int` (`PGInt4`), which is a foreign key pointing to the `id` field of the `foo` table.

Now let's say you have a Haskell function that uses `Opaleye` to get all the `bar`s associated with a given `foo`:

    getFooBars :: QueryArr Foo Bar
    getFooBars = proc foo -> do
        bar <- queryTable barTable -< ()
        restrict -< bar ^. fooId .== foo ^. id_
        returnA -< bar

(Let's say `fooId` and `id_` are lenses that get the `foo_id` field and `id` field of `bar` and `foo` respectively.)

If you did this naively, `bar ^. fooId` and `foo ^. id_` would both have type `Column PGInt4`. Which works, of course. But there's nothing stopping you accidentally typing `bar ^. barId .== foo ^. id_` by accident, and having it also type check (assuming the `bar` table also has a `barId` field of type `int` (`PGInt4`)).

What I want to do is to make `bar ^. fooId` have the type `Column (ID "foo")` and `bar ^. barId` have the type `Column (ID "bar")` (where `ID` is a type synonym in terms of `Tagged` as above). This prevents these types of programming errors.

In order to do that, I need these `Default` instances for `Tagged`, and I also need `instance QueryRunnerColumnDefault a b => QueryRunnerColumnDefault (Tagged s a) (Tagged s' b)`, which I'll submit as a separate patch to your `haskell-opaleye` project.

Does that make sense?

**Comment by duairc** [comment]
Seeing as you already merged the this branch, I've opened up a separate pull request for the `Tagged` instances (#11)

**Comment by tomjaguarpaw** [comment]
Thanks for the explanation.  I see what you are trying to do.

I like idea in spirit but in practice I don't think we should do things that way.  `PGInt4` and its companions (`PGBool`, `PGText`, etc.) are morally not of kind `*`.  We should only use them as though they were of some (imaginary) kind `PGType`.  `Column` is morally of kind `PGType -> *`.  (In fact I'm very tempted to make them literally be of another kind, using `DataKinds`.)

`Tagged` is of kind `k -> * - > *` so it does not fit in with what you want to do here.

An alternative that gets you most of the way to what you want to do (or maybe all the way, or maybe beyond) would be to define

    newtype ColumnID s = ColumnID (Column PGInt4)

In fact you won't even have to write any new instances if you take a slightly adjusted approach:

    type ColumnID s = Const (Column PGInt4) s

(and there are many other equivalent ways you might want to explore).

How does that sound?

**Comment by duairc** [comment]
I've played around with this a bit, and yeah, your type synonym with `Const` basically works. (I had to substitute `.===` for `.==`, but that's okay.) It does require the instances you've already accepted to work, but it doesn't require anything else special.

`Const` and `Tagged` are obviously very similar (`Tagged` is a flipped `Const`). Up until recently, one of the main differences between them was that `Tagged`'s phantom type was kind-polymorphic, while `Const`'s was not, but [I fixed that](https://phabricator.haskell.org/D1630).

However, I would like not to be tied to GHC >= 8 just for this, so I would like to be able to use `Tagged` the way you have used `Const` in your suggestion. Basically what I'm saying is, these instances are still useful for me, even if I'm not putting the `Tagged` inside the `Column` but around it instead.

**Comment by tomjaguarpaw** [comment]
OK, seems fine.  I merged it.

**Pull request merged**
