### PR TITLE
Added instances for Procompose

### PR DESCRIPTION
**Pull request by duairc**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks!  Can you rebase on the latest master and resubmit?  I had to fix a test error that was not your fault.

**Comment by duairc** [comment]
Done!

**Comment by tomjaguarpaw** [comment]
I've still got a bug.  I'll fix it and rebase your patch.

**Comment by tomjaguarpaw** [comment]
Merged, thanks.

**Pull request closed without merging**
