### PR TITLE
GHC 9.2 support

### PR DESCRIPTION
**Pull request by mithrandi**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Thanks! Does this mean that you are using product-profunctors with something other than Opaleye? If so I am curious what. Or does it mean you are trying to fix Opaleye for 9.2? If so then thanks!

**Comment by tomjaguarpaw** [comment]
Released: https://hackage.haskell.org/package/product-profunctors-0.11.0.3

**Comment by tomjaguarpaw** [comment]
Opaleye now supports 9.2: https://hackage.haskell.org/package/opaleye-0.8.0.1

**Comment by mithrandi** [comment]
Just Opaleye :smile_cat:

**Pull request closed without merging**
